# Generated by Django 6.0.2 on 2026-02-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='feedback_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='feedback_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('online', 'Online')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_marked_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='use_live_location',
            field=models.BooleanField(default=False),
        ),
    ]
