# Generated by Django 6.0.2 on 2026-02-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_feedback_rating_booking_feedback_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='provider_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
