# Generated by Django 6.0.2 on 2026-02-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='provider_certificates/'),
        ),
    ]
