# Generated by Django 6.0.2 on 2026-02-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_address_customuser_mobile_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='providers/certificates/'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='providers/images/'),
        ),
    ]
