# Generated by Django 6.0.2 on 2026-02-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='aadhaar_card',
            field=models.FileField(blank=True, null=True, upload_to='providers/aadhaar/'),
        ),
    ]
