# Generated by Django 6.0.2 on 2026-02-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_available_time_service_duration_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='service',
            name='available_days',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
