# Generated by Django 6.0.2 on 2026-03-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_add_available_days_remove_electrician'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='subcategory',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
